actions:
    - name: goto_waypoint
      interface_type: actionlib
      default_actionlib_topic: /move_base
      default_actionlib_msg_type: move_base_msgs/MoveBase
      default_actionlib_goal:
          target_pose.header.frame_id: "map"
          target_pose.pose.position.x: ($rosparam /rosplan_roadmap_server/rosplan_asap/wp/($pddlparam to))[0]
          target_pose.pose.position.y: ($rosparam /rosplan_roadmap_server/rosplan_asap/wp/($pddlparam to))[1]
          target_pose.pose.orientation.w: 1
    - name: moveto_table
      interface_type: actionlib
      default_actionlib_topic: /move_base
      default_actionlib_msg_type: move_base_msgs/MoveBase
      default_actionlib_goal:
          target_pose.header.frame_id: "map"
          target_pose.pose.position.x: ($rosparam /rosplan_roadmap_server/rosplan_asap/wp/wp24)[0]
          target_pose.pose.position.y: ($rosparam /rosplan_roadmap_server/rosplan_asap/wp/wp24)[1]
          target_pose.pose.orientation.w: 1